name: Update Browserslist Database

on:
  push:
    branches:
      - 'test/browserslist-updates'

env:
  branch-name: update/browserslist-db

jobs:
  close-existing-pr:
    name: Close existing PR
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch exists
        id: check-branch
        continue-on-error: true
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/${{ github.repository }}/git/ref/heads/${{ env.branch-name }}'
          method: 'GET'
          bearerToken: ${{ secrets.GITHUB_TOKEN }}
          customHeaders: '{"Accept": "application/vnd.github+json"}'

      - name: Delete branch
        if: steps.check-branch.outcome == 'success'
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ env.branch-name }}'
          method: 'DELETE'
          bearerToken: ${{ secrets.GITHUB_TOKEN }}
          customHeaders: '{"Accept": "application/vnd.github+json"}'
    outputs:
      response: ${{ steps.check-branch.outputs.response }}

  show-response:
    name: Show Response
    runs-on: ubuntu-latest
    needs: close-existing-pr
    steps:
      - name: Show Response
        run: |
          echo ${{ needs.close-existing-pr.outputs.response }}

  update-browserslist-database:
    name: Create PR containing Browserslist updates
    runs-on: ubuntu-latest
    needs: close-existing-pr
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Update Browserslist database and create PR if applicable
        uses: c2corg/browserslist-update-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.branch-name }}
          commit_message: 'Update Browserslist database.'
          title: 'Update Browserslist Database'
          body: Auto-generated by [browserslist-update-action](https://github.com/c2corg/browserslist-update-action/)
          base_branch: test/browserslist-updates
